[package]
name = "benchmarks"
edition = "2021"
publish = false

[dependencies]
roman-numerals-rs = { path = ".." }
# no dependencies

[dev-dependencies]
divan = { version = "0.1.16" }

[[bench]]
name = "benchmark"
harness = false
