target-version = "py39"  # Pin Ruff to Python 3.9
line-length = 88
output-format = "full"

[lint]
preview = true
select = ["ALL"]
ignore = [
    "COM812",  # trailing comma missing
    "ISC001",  # implicitly concatenated string literals on one line
    # Conflicts with ``ruff format``

    "CPY001",  # missing copyright notice at top of file
    # We don't use per-file copyright notices.

    "D107",  #  Missing docstring in `__init__`
    # Class docstrings are in the class body
]

[lint.per-file-ignores]
"roman_numerals/__init__.py" = [
    "DOC201",  # `return` is not documented in docstring
    "DOC501",  #  Raised exception `{exc}` missing from docstring
    # These don't yet support PEP 257 style field-lists.
]

"tests/*" = [
    "D",  # tests don't need docstrings
    "S101",  # pytest uses assert
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.isort]
forced-separate = [
    "tests",
]

[lint.pydocstyle]
convention = "pep257"

[lint.pycodestyle]
max-line-length = 95

[format]
preview = true
quote-style = "single"
